### ISSUE TITLE
Installation Lab

### ISSUE THREAD

**Issue by WinZerZ** [WinZerZ/SEBC#3]

**Comment by WinZerZ** [comment]
finished prepare machine, SYSTEM CONFIGURATION CHECK

**Comment by WinZerZ** [comment]
finished MYSQL HA

**Comment by WinZerZ** [comment]
finished setup local repository

**Comment by mfernest** [comment]
I assume your CM server is up and running?

**Comment by WinZerZ** [comment]
all of them are working, already committed CM screen shot and Local repo screenshot

**Comment by mfernest** [comment]
Please format your submissions in Markdown for readability. I've created a Pull Request with a file that shows how to do this.

**Comment by WinZerZ** [comment]
Please check again, I have fixed node ip format and cluster name

**Comment by mfernest** [comment]
Please take another look at the files in your `labs/` directory. Still not right.

**Comment by WinZerZ** [comment]
Oh sorry, I have fixed it.
PS. I see that your instruction said to upload file into installation/ . That is why I updated outside of labs/ directory.

**Comment by mfernest** [comment]
Hm. Well, that's a shame. I fixed those paths in the master repo -- thanks.

However, your files `1_preinstall.md` and `2_replica_working.md` are still not formatted properly.

**Comment by mfernest** [comment]
All better -- thank you.

🏆
